### ISSUE TITLE
Proxy tests for cheatcodes

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1794] opened 2023-04-18 13:12 UTC
I heard the word that in Cairo 1 we should use `replace_class` for proxy but I couldn't find any concrete examples so far.

May be helpful: https://github.com/Dev43/aa-cairo1

**Comment by cptartur** [comment] 2023-05-05 10:01
I think old proxy pattern should work exactly the same as it did in cairo0 assuming all required syscalls are already available.

Or you can basically define an `upgrade` method on your contract that calls `replace_class` and use that instead of proxy pattern

```cairo
#[external]
fn upgrade(new_contract_class: ClassHash) {
  // do some kind of owner verification
  replace_class_syscall(new_contract_class);
}
```

**Comment by MaksymilianDemitraszek** [comment] 2023-05-16 10:10
@karol-bisztyga What was the purpose of this issue? Do we need to write any proxy tests?

**Comment by karol-bisztyga** [comment] 2023-05-17 10:50
Yes, the point is to have proxy Cairo 1 tests.

**Comment by MaksymilianDemitraszek** [comment] 2023-05-19 11:08
Duplicate of https://github.com/software-mansion/protostar/issues/1383

**Closed by MaksymilianDemitraszek** 2023-05-19 11:08 UTC
