### ISSUE TITLE
Supporting multiple mock_call responses

### ISSUE THREAD

**Issue by starknetdev** [software-mansion/protostar#1565] opened 2023-03-06 10:41 UTC
I have a case in my contract where I have a random number generator that provides multiple random numbers within the same function invoke. When building tests in protostar I would like to force multiple of these outputs to check logic in each random path is working.

As suggested in a thread by karol, perhaps some support for arrays in mock call would work:

```
mock_call(addr, 'foo', [1,2,3])
foo() // returns 1
foo() // returns 2
foo() // returns 3
```
Or perhaps accept a formula to determine the new output with a starting value?

**Comment by MaksymilianDemitraszek** [comment] 2023-03-06 12:48
Seems useful, we will work on it, but cannot promise any timeline

**Comment by MaksymilianDemitraszek** [comment] 2023-04-24 18:20
Duplicate of #1251

**Closed by MaksymilianDemitraszek** 2023-04-24 18:20 UTC
